# Generated by Django 2.1.2 on 2018-10-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NLP_MAPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('Address', models.TextField()),
                ('intensity', models.IntegerField()),
            ],
        ),
    ]
