# Generated by Django 2.1.2 on 2018-10-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NLP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nlp_maps',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
