# Generated by Django 2.1.2 on 2018-10-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NLP', '0002_auto_20181025_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='nlp_maps',
            name='Remarks',
            field=models.CharField(default='Road Block', max_length=50),
        ),
    ]
